### ISSUE TITLE
Request: Ubuntu/Debian Package via Open Build Service

### ISSUE THREAD

**Issue by moriarty** [DOCGroup/ACE_TAO#530]
With OpenSuse or CentOS, installation is simple, because they are available in the via the Open Build Service.

```sudo zypper ar http://download.opensuse.org/repositories/devel:/libraries:/ACE:/micro/openSUSE_Tumbleweed/devel:libraries:ACE:micro.repo```

This also, means it's really simple to add in a Dockerfile.

 @jwillemsen is it possible to add Ubuntu?

Sorry if this is the wrong place for a request... But it looks like you're the maintainer of both
https://build.opensuse.org/project/users/devel:libraries:ACE

Thanks!

**Comment by jwillemsen** [comment]
There is packaging support for Ubuntu/Debian, but it is not 100% complete, it currently fails on OBS. ACE has been updated on Debian recently, hopefully with the next micro release we can fix this again on OBS but no guarantees because we don't have sponsoring for this kind of efforts at this moment. See in the ACE/debian directory for the files we have, pull requests for improvements or sponsoring is welcome.
