### ISSUE TITLE
ImR with per_client server activation results in hanging clients

### ISSUE THREAD

**Issue by jwillemsen** [DOCGroup/ACE_TAO#666]
When using the ImR with a per client server activation can result in hanging clients. This seem to happen when multiple clients very fast try to invoke the same server which results in multiple starts of the same server name, not all clients get a location forward back from the locator but they just hang forever

**Comment by jwillemsen** [comment]
For each per client activate server a new AAM is constructed but they all share the same Server_Info which means that when the first spawned server reports back that it is running it is updated for all AAM instances

**Comment by jwillemsen** [comment]
See #668 and #669

**Comment by pmesnier** [comment]
Hi Johnny, 
I'm sorry, it's been so long since I've considered this code I've lost all context. It looks like you were able to synthesize a fix, I trust that it will address the problem at hand. 

My original use case did not require per-client activations so while I tried to not break it, I didn't have much bandwidth to devote to it.
